### PR TITLE
Features/data reporter

### PR DESCRIPTION
**Pull request by dandm1**
Created some stub classes for a data reporter

### CODE REVIEW

**Comment by dandm1** [comment]
Hmm no - looks like I have misunderstood how the extensions assembly works.  Will have to try that again.

**Comment by Jasonkingsmill** [comment]
Yeah, sorry it’s very early in the concept development.
The extensions are designed to be class libraries found and loaded at application launch, decoupling them from the main application (so anybody can write an extension without recompiling the application).
The extension loader will enumerate directories within the main configured extension directory, and attempt to load the assembly with the same name as the directory. E.g., Extensions\FineOffset\FineOffset.dll. 
It will load all types implementing the IExtension interface (simply a marker interface) - all actual extension interfaces (IWeatherStation, IDataReporter etc..) should implement this interface. 
Your IDataReporter interface is somewhat similar to what I had in mind. 
I’ve been swamped lately but plan to start back on it again soon. Let me know if you would like to add more contributions and I can run you through what I had in mind.

**Comment by dandm1** [comment]
Hi Jason,




Thanks for the reply. 




I think I understand the structure now. I had wrongly assumed that the . Extensions DLL would contain actual extensions, rather than the interface definitions used to define extensions. It's not a difficult refactor, so hoping I will get a new pull request out later today.




I haven't got a lot of time, but interested to contribute where I can. Suspect I can get the hang of enough of it to add reasonable value until you cease to be swamped.




David




On Fri, Feb 22, 2019 at 10:17 AM +0000, "Jason Kingsmill" <notifications@github.com> wrote:












Yeah, sorry it’s very early in the concept development.


The extensions are designed to be class libraries found and loaded at application launch, decoupling them from the main application (so anybody can write an extension without recompiling the application).


The extension loader will enumerate directories within the main configured extension directory, and attempt to load the assembly with the same name as the directory. E.g., Extensions\FineOffset\FineOffset.dll.


It will load all types implementing the IExtension interface (simply a marker interface) - all actual extension interfaces (IWeatherStation, IDataReporter etc..) should implement this interface.


Your IDataReporter interface is somewhat similar to what I had in mind.


I’ve been swamped lately but plan to start back on it again soon. Let me know if you would like to add more contributions and I can run you through what I had in mind.

**Comment by dandm1** [comment]
Replaced with a refactored version. Closing this one.

**Pull request closed without merging**
